# Generated by Django 4.0.10 on 2024-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField()),
                ('userbio', models.CharField(max_length=100, null=True)),
                ('userlocation', models.CharField(max_length=100, null=True)),
                ('usertwitter', models.CharField(max_length=100, null=True)),
                ('repositories', models.ManyToManyField(to='repo.repository')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.ManyToManyField(to='repo.topic'),
        ),
    ]
